# By default, SwiftLint uses a set of sensible default rules you can adjust
disabled_rules: # rule identifiers to exclude from running
  - todo
  - private_subject
  - convenience_type
  - notification_center_detachment
  - multiple_closures_with_trailing_closure

opt_in_rules: # some rules are only opt-in
  - accessibility_label_for_image # Accessibility Label for Image
  - anyobject_protocol # AnyObject Protocol
  - array_init # Array Init
  - attributes # Attributes
  - balanced_xctest_lifecycle # Balanced XCTest life-cycle
  - capture_variable # Capture Variable
  - closure_body_length # Closure Body Length
  - closure_end_indentation # Closure End Indentation
  - closure_spacing # Closure Spacing
  - collection_alignment # Collection Element Alignment
  - comma_inheritance # Comma Inheritance Rule
  - conditional_returns_on_newline # Conditional Returns on Newline
  - contains_over_filter_count # Contains Over Filter Count
  - contains_over_filter_is_empty # Contains Over Filter Is Empty
  - contains_over_first_not_nil # Contains over first not nil
  - contains_over_range_nil_comparison # Contains over range(of) comparison to nil
  - convenience_type # Convenience Type
  - discarded_notification_center_observer # Discarded Notification Center Observer
  - discouraged_assert # Discouraged Assert
  - discouraged_none_name # Discouraged None Name
  - discouraged_object_literal # Discouraged Object Literal
  - empty_collection_literal # Empty Collection Literal
  - empty_count # Empty Count
  - empty_string # Empty String
  - empty_xctest_method # Empty XCTest Method
  - enum_case_associated_values_count # Enum Case Associated Values Count
  - expiring_todo # Expiring Todo
  - explicit_init # Explicit Init
  - explicit_self # Explicit Self
  - explicit_type_interface # Explicit Type Interface
  - extension_access_modifier # Extension Access Modifier
  - fallthrough # Fallthrough
  - fatal_error_message # Fatal Error Message
  - file_header # File Header
  - file_name_no_space # File Name No Space
  - file_types_order # File Types Order
  - first_where # First Where
  - flatmap_over_map_reduce # FlatMap over map and reduce
  - force_unwrapping # Force Unwrapping
  - ibinspectable_in_extension # IBInspectable in Extension
  - identical_operands # Identical Operands
  - implicit_return # Implicit Return
  - implicitly_unwrapped_optional # Implicitly Unwrapped Optional
  - indentation_width # Indentation Width
  - joined_default_parameter # Joined Default Parameter
  - last_where # Last Where
  - legacy_multiple # Legacy Multiple
  - legacy_objc_type # Legacy Objective-C Reference Type
  - literal_expression_end_indentation # Literal Expression End Indentation
  - lower_acl_than_parent # Lower ACL than parent
  - modifier_order # Modifier Order
  - multiline_arguments # Multiline Arguments
  - multiline_arguments_brackets # Multiline Arguments Brackets
  - multiline_function_chains # Multiline Function Chains
  - multiline_literal_brackets # Multiline Literal Brackets
  - multiline_parameters # Multiline Parameters
  - multiline_parameters_brackets # Multiline Parameters Brackets
  - nimble_operator # Nimble Operator
  - nslocalizedstring_key # NSLocalizedString Key
  - nslocalizedstring_require_bundle # NSLocalizedString Require Bundle
  - number_separator # Number Separator
  - object_literal # Object Literal
  - operator_usage_whitespace # Operator Usage Whitespace
  - optional_enum_case_matching # Optional Enum Case Match
  - overridden_super_call # Overridden methods call super
  - override_in_extension # Override in Extension
  - pattern_matching_keywords # Pattern Matching Keywords
  - prefer_self_in_static_references # Prefer Self in Static References
  - prefer_self_type_over_type_of_self # Prefer Self Type Over Type of Self
  - prefer_zero_over_explicit_init # Prefer Zero Over Explicit Init
  - private_action # Private Actions
  - private_outlet # Private Outlets
  - private_subject # Private Combine Subject
  - prohibited_interface_builder # Prohibited Interface Builder
  - prohibited_super_call # Prohibited calls to super
  - quick_discouraged_call # Quick Discouraged Call
  - quick_discouraged_focused_test # Quick Discouraged Focused Test
  - quick_discouraged_pending_test # Quick Discouraged Pending Test
  - raw_value_for_camel_cased_codable_enum # Raw Value For Camel Cased Codable Enum
  - redundant_nil_coalescing # Redundant Nil Coalescing
  - required_enum_case # Required Enum Case
  - return_value_from_void_function # Return Value from Void Function
  - single_test_class # Single Test Class
  - sorted_first_last # Min or Max over Sorted First or Last
  - sorted_imports # Sorted Imports
  - static_operator # Static Operator
  - strict_fileprivate # Strict fileprivate
  - strong_iboutlet # Strong IBOutlet
  - switch_case_on_newline # Switch Case on Newline
  - test_case_accessibility # Test case accessibility
  - toggle_bool # Toggle Bool
  - typesafe_array_init # Type-safe Array Init
  - unavailable_function # Unavailable Function
  - unneeded_parentheses_in_closure_argument # Unneeded Parentheses in Closure Argument
  - unowned_variable_capture # Unowned Variable Capture
  - untyped_error_in_catch # Untyped Error in Catch
  - unused_declaration # Unused Declaration
  - unused_import # Unused Import
  - vertical_parameter_alignment_on_call # Vertical Parameter Alignment On Call
  - vertical_whitespace_between_cases # Vertical Whitespace Between Cases
  - vertical_whitespace_closing_braces # Vertical Whitespace before Closing Braces
  - vertical_whitespace_opening_braces # Vertical Whitespace after Opening Braces
  - weak_delegate # Weak Delegate
  - xct_specific_matcher # XCTest Specific Matcher
  - yoda_condition # Yoda condition rule

custom_rules:
  sf_safe_symbol:
    name: "Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
    severity: warning

included:
  - Modules
  - github

excluded:
  - Modules/Package.swift

# Rules configuration
identifier_name:
  excluded:
    - id
    - no

type_name:
  allowed_symbols:
    - _

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 120
  error: 120

closure_body_length:
  warning: 200
  error: 250

function_body_length:
  warning: 50
  error: 60

reporter: "xcode"
